version: '3'
services:
  redis:
    image: "redis:alpine"
    expose:
      - "6379"

  webapp:
    build:
      dockerfile: Dockerfile
      context: ./appboxo
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./appboxo:/app
    ports:
      - "8000:8000"
    links:
      - "redis"